# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  react: thefrontside/react@0.2.0
parameters:
  parameter:
    default: "world"
    type: string  
jobs:
  echo-things:
    executor: react/default 
    steps:
      - run: echo "Hello <<parameters.to>>"
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  build-things:
    # Run the welcome/run job in its own container
    jobs:
      - react/install
      - react/build:
          requires:
            - react/install
  test-things:
    jobs:
      - echo-things
