# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  react: thefrontside/react@0.2.0
  slack: circleci/slack@4.4.4
jobs:
  example-job:
    executor: react/default
    steps:
      - react/install
      - react/build
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
      - slack/notify:
          event: fail
          template: basic_fail_1
  test-context:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - run: echo $TEST
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - example-job:
          context:
            - Slack
  daily:
    jobs:
      - react/install
      - example-job
    triggers:
      - schedule:
          cron: 0 16 * * *
          filters:
            branches:
              only:
                - main
  daily-workflow:
    jobs:
      - react/install
      - example-job
    triggers:
      - schedule:
          cron: 0 22 * * *
          filters:
            branches:
              only:
                - main
